"attribute" = { fg = "blue", modifiers = ["italic"] }
"ui.virtual.wrap"="softwrap"
"keyword" = "keyword"
"keyword.control.conditional" = { fg = "conditional", modifiers = ["italic"] }
"keyword.directive" = "magenta" # -- preprocessor comments (#if in C)

"namespace" = { fg = "namespace", modifiers = ["bold"] }

"punctuation" = "gray06"
"punctuation.delimiter" = "gray06"

"operator" = "operator"
"special" = "yellow"

"variable" = {fg="whiteish", modifiers = ["bold"]}
"variable.builtin" = "bright_blue"
"variable.parameter" = {fg="white", modifiers=["italic"]}
"variable.other.member" = "white"

"type" = "bright_blue"
"type.builtin" = "magenta"
"type.enum.variant" = "magenta"

"constructor" = "yellow"

"function" = {fg="cyan", modifiers = ["italic"]}
"function.macro" = "bright_pinkish"
"function.builtin" = "support_function"

"tag" = "tag"
"comment" = { fg = "hard_gray", modifiers = ["italic"] }

"string" = "string"
"string.regexp" = "green"
"string.special" = "yellow"

"constant" = "constant"
"constant.builtin" = "yellow"
"constant.numeric" = "numeric"
"constant.character.escape" = "pinkish"

# used for lifetimes
"label" = "yellow"

"markup.heading.marker" = { fg = "gray06" }
"markup.heading" = { fg = "bright_blue", modifiers = ["bold"] }
"markup.list" = "gray06"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "green", modifiers = ["underlined"] }
"markup.link.text" = { fg = "blue", modifiers = ["italic"] }
"markup.raw" = "yellow"

"diff.plus" = "bright_green"
"diff.minus" = "red"
"diff.delta" = "bright_blue"

"ui.background" = { bg = "black" }
"ui.background.separator" = { fg = "whiteish" }

"ui.linenr" = { fg = "gray04" }
"ui.linenr.selected" = { fg = "whiteish" }

# "ui.statusline" = { fg = "status_line_fg", bg = "black" }
# "ui.statusline.inactive" = { fg = "black", bg = "gray", modifiers = ["dim"] }
"ui.statusline" = { fg = "black", bg = "white", modifiers = ["bold"]}
"ui.statusline.inactive" = { fg = "white", bg = "black_hint", modifiers = ["italic", "bold"] }
"ui.statusline.normal" = { fg = "black", bg = "pinkish", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "black", bg = "blue", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "black", bg = "magenta", modifiers = ["bold"] }

"ui.popup" = { bg = "gray01" }
"ui.window" = { fg = "gray02" }
"ui.help" = { bg = "gray01", fg = "white" }

"ui.text" = { fg = "whiteish" }
"ui.text.focus" = { fg = "whiteish" }

"ui.virtual" = { fg = "gray02" }
"ui.virtual.ruler" = {bg="gray02"}
"ui.virtual.indent-guide" = { fg = "gray02" }
"ui.virtual.inlay-hint" = { fg = "gray03" }
"ui.virtual.jump-label"={ fg="red", modifiers = ["bold"]}


"ui.selection" = { bg = "gray03" }
"ui.selection.primary" = { bg = "gray03" }

"ui.cursor" = {fg="black", bg = "cursor" }
"ui.cursor.match" = { fg = "yellow", modifiers = ["bold", "underlined"] }
"ui.cursorline.primary" = { bg = "gray01" }

"ui.cursor.primary.normal" = { fg = "black", bg = "blue" }
"ui.cursor.primary.insert" = { fg = "black", bg = "green" }
"ui.cursor.primary.select" = { fg = "black", bg = "magenta" }

"ui.highlight" = { bg = "gray02" }

"ui.menu" = { fg = "white", bg = "black" }
"ui.menu.selected" = { fg = "bluish_white", bg = "gray03" }
"ui.menu.scroll" = { fg = "gray04", bg = "gray01" }

diagnostic = { modifiers = ["underlined"] }

warning = "yellow"
error = "mild_red"
info = "bright_blue"
hint = "cyan"

[palette]
black = "#151726"
black_hint = "#15131a"
string="#a78bfa"
mild_red="#ee8679"

whiteish = "#e0dcdc"
bluish_white = "#cac9dd"
green = "#90b99f"
bright_green = "#9dc6ac"
yellow = "#f8d2c9"
blue = "#aca1cf"
bright_blue = "#b9aeda"
magenta = "#e29eca"
pinkish = "#ea83a5"
bright_pinkish = "#f591b2"
white = "#c1c0d4"
gray01 = "#292A37" # cursorline
gray02 = "#292A37" # separator
gray03 = "#3e3e43" # selector
gray04 = "#57575f" # line number
gray06 = "#9998a8"
gray07 = "#c1c0d4"
hard_gray="#808080"
red="#e78284"
cyan="#4fdcff"
support_function="#e5c890"
constant="#8eb6f5"
tag="#9898a6"
keyword="#8eb6f5"
namespace= "#c58fff"
numeric= "#e9c46a"
status_line_fg = "#ffffff"
operator="#8eb6f5"
softwrap="#808080"
conditional="#a8a29e"
cursor="#e5c890"

