CompileFlags:
  Add: [-xc++, -std=c++20, -Wall, -Wno-missing-prototypes]
  Remove: -mabi
Diagnostics:
  ClangTidy:
    Add: [performance*, modernize*]
    Remove: [modernize-use-trailing-return-type]
---
If:
  PathMatch: [.*\.c, .*\.h]
CompileFlags:
  Add: [-xc, -std=c17, -Wall, -Wno-missing-prototypes]
  Remove: -mabi
